### PR TITLE
draft: problem with authenticating users

### PR DESCRIPTION
**Pull request by boekhorstb1**
- while trying to connect the simportal to the dev-composer-setup I found this a possible issue

### CODE REVIEW

**Comment by ralflang** [comment]
This is not the solution. 
The interface for a middleware demands that it always will produce a ResponseInterface either on its own or by delegation.

Please create a reproducer unit test for your actual problem.

**Comment by boekhorstb1** [comment]
Thanks, yes I think the problem lies elsewhere. It seems to be solved in another way (trying to find out why). Will reopen this when the issue resurfaces.

**Comment by boekhorstb1** [comment]
Hi, Im reopening:

- when looking at AuthHttpBasic.php line 68 `$this->driver->authenticate` does not work although Im trying to login with my admin user (I can log in to Horde with no problems). The $driver is Horde_Auth_Basic, an abstract class, which calls `$this->_authenticate($userId, $credentials);`, a method which in turn is not extended/defined by AuthHttpBasic ... 

- trying to create unit test but probably autoloader is not working correctly:

````
PHP Fatal error:  Trait 'Horde\Core\Test\Middleware\SetUpTrait' not found in /srv/www/horde/vendor/horde/core/test/Middleware/AppFinderTest.php on line 23
````

**Comment by ralflang** [comment]
You need to create this middleware through a factory which injects the correct implementation of Horde_Auth_Base as the auth driver. The internal workings of the auth driver are out of scope for the authentication middleware.

The authentication middleware is about unpacking the authentication string and supplying it to the auth API driver. The driver in turn may use ldap, sql or whatever.

**Comment by boekhorstb1** [comment]
> You need to create this middleware through a factory which injects the correct implementation of Horde_Auth_Base as the auth driver. The internal workings of the auth driver are out of scope for the authentication middleware.
> 
> The authentication middleware is about unpacking the authentication string and supplying it to the auth API driver. The driver in turn may use ldap, sql or whatever.

ok thank you!

**Pull request closed without merging**
